name: Build and Publish openrag distribution to PyPI 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: openrag-package-distribution
          path: dist

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/openrag

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: openrag-package-distribution
          path: openrag-package-distribution

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Publish distribution 📦 to PyPI
        run: |
          python3 -m pip install twine
          python3 -m twine upload --repository pypi --username koleshjr --password ${{ secrets.PYPI_API_TOKEN }} openrag-package-distribution/*