name: Build and Publish open_rag distribution to PyPI

on:
  merge:
    branches:
      - main

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip and install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: open_rag-package-distribution
          path: dist

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/open_rag

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: open_rag-package-distribution
          path: open_rag-package-distribution

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Publish distribution 📦 to PyPI
        run: |
          python -m pip install twine
          python -m twine upload --repository pypi --username Kolesh --password ${{ secrets.PYPI_API_TOKEN }} open_rag-package-distribution/*
